### ISSUE TITLE
Feature proposal - $client->send() - return a Promise

### ISSUE THREAD

**Issue by FGIKCM** [reactphp/datagram#32]
For now, there is no way with the client to send data, THEN close the stream when everything is sent. The `$client->send('message)` is not in a Promise, so doing the following will not (always) work, as the stream may be closed before everything is sent:
```php
$client->send('chain1');
$client->send('chain2');
$client->close();
```

Should it be possible to have a similar function, which would returns a Promise? This way, we would have a clean way to send messages, THEN closing the stream.
For example:
```php
$client->sendInPromise('chain1chain 2')->then(function() use ($client) {$client->close()});
```

**Comment by clue** [comment]
Hey @FGIKCM, excellent question!

It looks like this boils down to a lack of good documentation - this is already supported by using the `end()` method instead of `close()`. Unlike the `close()` method, the `end()` method will wait for all outgoing data to be sent and only then `close()` the socket resource.

I hope this helps :+1:

**Comment by FGIKCM** [comment]
Great, Thank you!
